### PR TITLE
not-maintainer.jinja2.md: Replace a word

### PR DESCRIPTION
**Pull request by EverWinter23**
username-->target

Closes https://github.com/coala/corobo/issues/479

# Reviewers Checklist

- [x] Appropriate logging is done.
- [x] Appropriate error responses.
- [x] Handle every possible exception.
- [x] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [x] See that 100% coverage is there.
- [x] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by EverWinter23** [comment]
Made the requested changes.

**Comment by ishanSrt** [comment]
@EverWinter23 I don't know if the shortlog, `Replace a word` is suitable for this as this does not seem to be just any documentation. Try if you can change while still being inside the word limit. 😉
Otherwise looks good!

**Comment by Makman2** [comment]
Aren't some code changes required? So the new format-placeholder is correctly filled?

**Comment by andrewda** [comment]
@Makman2 nope, `target` is already used, this is just a little typo in the template: https://github.com/coala/corobo/blob/master/plugins/labhub.py#L119-L124

**Comment by Makman2** [comment]
ack fdd4bff1c44bfa3258707ce49b56a0709ad7782a

**Comment by Makman2** [comment]
Reactivated gitmate again, doing a rebase to trigger hooks.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by sils** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by sils** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by Makman2** [comment]
Hmm it's already rebased, @EverWinter23 could you repush with `git commit --amend --no-edit && git push -f`? Then the SHA is regenerated and a new build cycle is triggered.

**Comment by EverWinter23** [comment]
@Makman2 @sils Done

**Comment by EverWinter23** [comment]
@Makman2 @sils Done

**Comment by Makman2** [comment]
reack a88a96a81563e6693b66359eedce3e9ae7330de4

**Comment by Makman2** [comment]
@gitmate-bot ff

**Comment by sils** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by sils** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by EverWinter23** [comment]
YES!!

**Pull request merged**
