### PR TITLE
.coafile: Fix a typo

### PR DESCRIPTION
**Pull request by bhavishyagopesh**
Changes `[commits]` to `[commit]`.

Closes https://github.com/coala/corobo/issues/451

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@gitmate-bot rebase

**Comment by bhavishyagopesh** [comment]
@meetmangukiya  rebase-done

**Comment by bhavishyagopesh** [comment]
@meetmangukiya I'm not sure if failure is due to related reasons??

**Comment by jayvdb** [comment]
ack https://github.com/coala/corobo/pull/452/commits/f3ba1ec9ccd48f4fd1fee531ce970ecbe31a2aee

**Pull request merged**
