### PR TITLE
gsoc: setup.cfg: Move the tests to testpaths key

### PR DESCRIPTION
**Pull request by meetmangukiya**
Closes https://github.com/coala/corobo/issues/115

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by RJ722** [comment]
ack 78e04795286a4c604d265f64b752b7e42651b9b0

**Comment by meetmangukiya** [comment]
reack 78e04795286a4c604d265f64b752b7e42651b9b0

**Comment by meetmangukiya** [comment]
reack 78e04795286a4c604d265f64b752b7e42651b9b0

**Comment by nkprince007** [comment]
ack 78e04795286a4c604d265f64b752b7e42651b9b0

**Comment by sils** [comment]
ack 78e0479

**Comment by meetmangukiya** [comment]
ack 78e04795286a4c604d265f64b752b7e42651b9b0

**Comment by meetmangukiya** [comment]
@rultor merge

**Pull request merged**
