### PR TITLE
config.py: Limit render test in test room

### PR DESCRIPTION
**Pull request by mohitkyadav**
Add ACCESS_CONTROLS for render test command

Closes https://github.com/coala/corobo/issues/359

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by mohitkyadav** [comment]
Please check these screenshots. [this](https://drive.google.com/open?id=1kYYDoly-zde6xkD7RXxov2SNblAluE0E) && [this](https://drive.google.com/open?id=1_iqvqk5Bk_kQfhgk5z8GUYqmQ-sWe5nL)
I am confused about the allowed rooms, should we allow `render test` in `coala/corobo`?

**Comment by Vamshi99** [comment]
@mohitkyadav Please add tests

**Comment by mohitkyadav** [comment]
@jayvdb @meetmangukiya I've made some changes please take a look. I think the problem is with switching the test bot to a public room, take a look at, [this](https://github.com/mohitkyadav/corobo/blob/render-test-private/tests/access_control_test.py#L15), after changing the room next test, [this one](https://github.com/mohitkyadav/corobo/blob/render-test-private/tests/access_control_test.py#L17) still passes. The ACLs are working perfectly but can't say how to change the room of bot to a public room, after all it's still in the private chat. Please correct me if I'm wrong.

**Comment by mohitkyadav** [comment]
@Vamshi99 take a look.

**Comment by nemaniarjun** [comment]
Hey? Are you still on this?
If yes: Tests are failing!

**Comment by mohitkyadav** [comment]
nope @nemaniarjun I tried but couldn't find a way to test this.

**Comment by nemaniarjun** [comment]
@mohitkyadav  @Makman2 please close this PR :)

**Pull request closed without merging**
