### PR TITLE
git_stats.plug: Fix spelling from 'GitLub' to 'GitLab'

### PR DESCRIPTION
**Pull request by rhartung**
Change spelling on line 6 of git_stats.plug file from GitLub to GitLab
fixes <https://github.com/coala/corobo/issues/490>

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by jayvdb** [comment]
Please replace "fixes <#490>" with a blank line and `Fixes https://github.com/coala/corobo/issues/490` , per http://coala.io/commit .

**Comment by Vamshi99** [comment]
ack 19eac78

**Comment by prnvdixit** [comment]
unack 19eac78e5261f0b5cbc8d18cb690b42c6f499ba5

**Comment by rhartung** [comment]
Thanks for the feedback, should be good to go 😄

**Comment by rhartung** [comment]
The commit message I submitted most recently follows the instructions in https://coala.io/commit - 

"
* setup.py: Change bears’ entrypoint: Describe the change in
maximum of 50 characters.
* This entrypoint.. ..for this: Describe the reasoning of your changes
in maximum of 72 characters per line.
* Closes https://github.com/coala/coala/issues/5861: Mention the URL
of the issue it closes or fixes.
"

Can you clarify what you mean by removing the body?

**Comment by ishanSrt** [comment]
the body is optional and should only specify things that are not self explanatory

**Comment by rhartung** [comment]
OK, that makes sense - message updated to be more concise 👍

**Comment by ishanSrt** [comment]
ack https://github.com/coala/corobo/pull/491/commits/28d139e84f6361af811fdab358f181a42934df09

**Comment by prnvdixit** [comment]
@rhartung Umm... I would've recommended (and I see that you did in previous commit) to mention the changes that you have done (```This changes the spelling of "GitLub" to "GitLab".```) since we have quite a lot of "Fix spelling mistake" commits :wink:.
But, keeps things as they are for now - might be good to go anyway too :smile:
Good work! :+1:

**Comment by rhartung** [comment]
@prnvdixit ok lmk if you want me to switch it back to the more descriptive version, but I'll leave it as is for now, thx!

**Pull request merged**
