### PR TITLE
Adding ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by attilanagy**
# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by palash25** [comment]
The issue link does not belong in the shortlog please add it after a newline

**Comment by attilanagy** [comment]
@palash25 Thanks for the update. Reword is done.

**Comment by palash25** [comment]
Looks fine to me. May I ask why do you want to skip ci @attilanagy ?

**Comment by attilanagy** [comment]
@palash25 Travis builds are failing but that's unrelated to this change. That's why I add the '[skip ci]' statement.

**Comment by jayvdb** [comment]
Please review your commit message to follow http://coala.io/commit

**Comment by attilanagy** [comment]
@jayvdb Thanks for your update. Reword is done. The statement '[skip ci]' is removed.

**Comment by jayvdb** [comment]
The short log also needs to be changed to something like `ISSUE_TEMPLATE: Create with basic instructions`

**Comment by attilanagy** [comment]
@jayvdb Thanks. Another reword is done.

**Comment by jayvdb** [comment]
ack c0acd51

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
