### PR TITLE
Change username to target | Issue #479

### LINKED ISSUE #479: Change username to target
Change username to target in `https://github.com/coala/corobo/blob/master/plugins/templates/labhub/errors/not-maintainer.jinja2.md`
label: difficulty/newcomer

### PR DESCRIPTION
**Pull request by HarendraSingh22**
Fixes #479

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by Vamshi99** [comment]
@HarendraSingh22 Follow commit guidelines https://coala.io/commit . Also, your PR should have only 1 commit, you can squash your commits, see http://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

**Comment by andrewda** [comment]
Rebase, squash, and edit your commit message and this'll be good to merge!

**Comment by Lorax6** [comment]
how do u do this? : O

**Comment by andrewda** [comment]
Rebase: `git pull --rebase upstream master` assuming upstream is your remote. 

Squash: `git rebase -i HEAD~2` and change `pick` to `fixup` on the second commit. 

Change: `git commit --amend` and change the message. 

There's also plenty of guides online on doing all this if you can't figure it out.

**Comment by HarendraSingh22** [comment]
I am a newbie. Just realised I could have asked. I was fearing asking such basic stuff

**Comment by HarendraSingh22** [comment]
Sending in a new PR

**Comment by HarendraSingh22** [comment]
See #497

**Pull request closed without merging**
