### PR TITLE
answers/requirements.txt: Remove unused nltk 

### PR DESCRIPTION
**Pull request by jennyjj**
Closes https://github.com/coala/corobo/issues/593

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by nvzard** [comment]
@jennyjj which issue are you trying to solve?

**Comment by Man-Jain** [comment]
Also the dependency isn't removed. You added it again in the second commit.

**Comment by jennyjj** [comment]
The issue is coala/corobo#593

**Comment by jennyjj** [comment]
Hi, I squashed one into one commit (so there are two commits combined).  I somehow deleted one commit (there were originally three).  I hope this is ok.  I believe it is all one commit now.

**Comment by jayvdb** [comment]
If you have a look at your published commit, it is now empty.

You can see it online at https://github.com/coala/corobo/pull/620/files

Make the change again, and amend your commit, and re-push.

**Comment by jennyjj** [comment]
Ok, I think I did it right this time.

**Comment by jennyjj** [comment]
Hi everyone, Thanks for your patience.  I have changed the https line slightly.  I hope all is fine now.

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack a90f335

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
