### PR TITLE
Fix semaphore builds

### PR DESCRIPTION
**Pull request by Vamshi99**
Update `org.iter_teams` to `org.teams` as per
the new release notes of github3.py v1.0.0

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by Vamshi99** [comment]
Link to Release notes: https://github.com/sigmavirus24/github3.py/blob/bf44c16510be84db7ec21cd7b2ae791626dc488c/LATEST_VERSION_NOTES.rst

**Comment by jayvdb** [comment]
You need to update `requirements.txt`

**Comment by Vamshi99** [comment]
@jayvdb Changed accordingly.

**Comment by jayvdb** [comment]
ack https://github.com/coala/corobo/pull/514/commits/583785c7c710bff930cb295c44da5321c4a90e17

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
