### PR TITLE
Adding space issue#250

### PR DESCRIPTION
**Pull request by Raman1121**
#250 explain: Add missing whitespace
# Reviewers Checklist

- [x] Appropriate logging is done.
- [x] Appropriate error responses.
- [x] Handle every possible exception.
- [x] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [x] See that 100% coverage is there.
- [x] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@Raman1121 please follow commit guidelines http://coala.io/commit 

Change the commit message to : `explain: Add missing whitespace`

**Comment by meetmangukiya** [comment]
@Raman1121 bump

**Comment by swapagarwal** [comment]
@Raman1121 ping

**Comment by jayvdb** [comment]
@Raman1121 , please fix your PR, or it will be discarded so a Google Code-in high school student can do it properly.

**Pull request closed without merging**
