### PR TITLE
README.md: Remove Travis Badge

### PR DESCRIPTION
**Pull request by ysahil97**
Discards Travis Badge as it is not used here

Fixes https://github.com/coala/corobo/issues/487

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by jayvdb** [comment]
This is a continuation of https://github.com/coala/corobo/pull/493 .  Your commit message still doesnt comply with http://coala.io/commit .  Please fix

**Comment by jayvdb** [comment]
If you close this PR, and start a new one, you will be removed from the organisation.

**Comment by jayvdb** [comment]
unack https://github.com/coala/corobo/pull/494/commits/95060cdb16cea2f89e12af39faa671c041f2e76e

**Comment by jayvdb** [comment]
This is not a correct rebase.  You should only have one commit in this PR.  Your commit.

Easiest way to fix this is to

1. use `git reset` to remove the recent commits in your local git until `git log` shows "28d139e84" as the most recent commit.
2. make your changes again
3. `git push --force`

**Comment by ysahil97** [comment]
I had updated my fork repository which had one additional commit updated in source repository yesterday. Should I ignore that commit?

**Comment by jayvdb** [comment]
ack https://github.com/coala/corobo/pull/494/commits/d66c027199ff2924a609a281fdfcff654c58416b

**Pull request merged**
