### PR TITLE
Changes to the requirements to be a developer

### LINKED ISSUE #425: Update corobo message accordingly if a newcomer tries to assign a issue above `difficulty/low` level.
Opened by @im-Nishant at [Gitter](https://gitter.im/coala/corobo?at=5a2038353c69dd4917097b7b)

### PR DESCRIPTION
**Pull request by alindsharmasimply**
Closes #425

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

Updated corobo message if a newcomer tries to assign an issue above 'difficulty/low' level.

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Which issue does this PR resolve? You'll have to reference it to the issue link. For reviewers to review.
Please read the commit guidelines.

**Comment by alindsharmasimply** [comment]
Oh yeah thanks!
Now should I edit my last commit as explained in the guide, or is there another way to correct it?

**Comment by mridubhatnagar** [comment]
You'll have ti amend your commit message. Check Git Basics or Newcomers Docs for that. You'll have to amend your commit message and then do a force push. git commit --amend

**Comment by alindsharmasimply** [comment]
Is this one OK @mridubhatnagar ?

**Comment by jayvdb** [comment]
unack https://github.com/coala/corobo/pull/467/commits/1a41601d80a381c5219f29695b6a507efeff16ee

**Comment by alindsharmasimply** [comment]
Thanx for the specs @jayvdb !
Glad to have got it reviewed.
Now I suppose I'll make changes in the code, add it, amend my last commit, and then force push through this same request. The procedure mentioned in the guide to be taken after PR rejection.
Correct?

**Comment by jayvdb** [comment]
Yup; just reuse this PR ; continue as normal.  The only change is you now have a clearer issue to work on.

**Comment by jayvdb** [comment]
Abandoned PR.

**Pull request closed without merging**
