### PR TITLE
Allow developers to invite newcomers

### PR DESCRIPTION
**Pull request by Vamshi99**
Closes https://github.com/coala/corobo/issues/322

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by jayvdb** [comment]
Need to update the tests, and also .. only allow invites to people "if they are a member of the room"

**Comment by Vamshi99** [comment]
@meetmangukiya Can you help me with the tests?

**Comment by jayvdb** [comment]
@Vamshi99 @meetmangukiya this is kinda urgent. We could disable auto invite and let our developers help manage the load of inviting with a revised onboarding process.

**Comment by jayvdb** [comment]
Can we test this using IRC backend instead ?

**Comment by Makman2** [comment]
Why closing? :)

**Pull request closed without merging**
