### PR TITLE
searchdocs_test: change http to https

### PR DESCRIPTION
**Pull request by ankitb073**
Closes https://github.com/coala/corobo/issues/579

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by ankitb073** [comment]
Can anyone help me to rectify what is wrong with this?

**Comment by nvzard** [comment]
@ankitb073 It might look overwhelming, but go through the logs once and check where the test's fails.
Also, check the `searchdocs` plugin and make the changes required to return a `https` link. :)

**Comment by nvzard** [comment]
@ankitb073 ping. Come on finish it up, you are really close ;)

**Comment by jayvdb** [comment]
Abandoned.

**Pull request closed without merging**
