### PR TITLE
labhub.py: Change the spellings of 'eligility' to 'eligibility' at lines 315 and 336

### PR DESCRIPTION
**Pull request by GnohChengYi**
# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by jayvdb** [comment]
Please follow our commit guideline  http://coala.io/commit

**Comment by Vamshi99** [comment]
@GnohChengYi You need to add reference to the issue which you are fixing. You can edit the commit message using `git commit --amend`. Also your commit shortlog length should not greater than 70. See 
http://coala.io/commit properly.

**Comment by jayvdb** [comment]
Your commit message hasnt been updated; see https://github.com/coala/corobo/pull/478/commits

**Comment by jayvdb** [comment]
This was fixed as part of https://github.com/coala/corobo/issues/257

**Pull request closed without merging**
