### PR TITLE
labhub: Add missing whitespace

### LINKED ISSUE #214: Whitespace missing in invite developer success message difficulty/newcomer
Opened by @jayvdb

### PR DESCRIPTION
**Pull request by vaibhavgarg11**
changed ourcommunity to our community
Closes #214

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@vaibhavgarg1 amend the commit and add `Closes` tag. `git commit --am`

**Comment by vaibhavgarg11** [comment]
I mentioned closes #266 in the changes made, do you want me to add in the commit message ?

**Comment by SanketDG** [comment]
@vaibhavgarg11 yup see https://coala.io/commit

**Comment by vaibhavgarg11** [comment]
Changed the commit message using `git commit --am`

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 please force push as well

**Comment by vaibhavgarg11** [comment]
@meetmangukiya using `git push -f origin patch` right ?

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 yes

**Comment by vaibhavgarg11** [comment]
@meetmangukiya did that

**Comment by vaibhavgarg11** [comment]
@meetmangukiya Is there something that needs to be done for this PR ?

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 thanks for adding the `Closes` tag, now there are conflicts(sorry), resolve and push please

**Comment by vaibhavgarg11** [comment]
@meetmangukiya  How do I see what the conflicts are and then how to resolve them
?

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 you can use `git-mergetool` and google about how to solve conflicts

**Comment by vaibhavgarg11** [comment]
@meetmangukiya rebased `patch` and resolved conflicts, please review

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 awesome work resolving conflicts!

**Comment by meetmangukiya** [comment]
ack ca5aecf

**Comment by meetmangukiya** [comment]
@rultor merge

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 your PR is being merged :tada:

**Pull request merged**
