### PR TITLE
[WIP] labhub.py: Prevent duplicate issue title

### PR DESCRIPTION
**Pull request by manu-chroma**
Before opening a new issue, check for duplicate
issue title in the repo and prevent from opening
if there's any.

Taking a shot at https://github.com/coala/corobo/issues/291. Am I on the right track?

cc: @meetmangukiya @jayvdb 

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by yashovardhanagrawal** [comment]
I think you're on the right track, but it's not necessary for a person to write the exact same title for a duplicate issue
can we do something for that? 
maybe there's some tool available that can sort this out...

**Comment by meetmangukiya** [comment]
@manu-chroma i don't particularly like comparing the title with ever issue in the issue tracker. This way each time I file a new issue in coala repo, at least 500 issues will be compared :O and also, we'll hit API rate limit way before that.

**Comment by SanketDG** [comment]
This is not a good way of checking for duplicate issues, there are a lot of things like caching and nlp implemented to detect duplicate issues effficiently.

**Comment by manu-chroma** [comment]
Thanks for the feedback everyone. 

@meetmangukiya I'm making one API call per try for opening a new issue, so I don't it should hit the API limit. 
@SanketDG I agree simple checking is not a good approach. Can you link me to any NLP/caching tools which I might use in this situation?

**Comment by meetmangukiya** [comment]
@manu-chroma you are searching issues for complete repo, you are essentially making one API call for each issue data(if the data is not available in the response of search call) and more calls for each page(in pagination). 

I think you might need to inspect `search_issues` function in `IGitt`. I'll take a good look at it later

**Comment by meetmangukiya** [comment]
@manu-chroma do you still want to work on this PR, else close it. :)

**Pull request closed without merging**
