### PR TITLE
Add deployment script

### PR DESCRIPTION
**Pull request by yukiisbored**
This script is in charge of doing the actual deployment and it's
executed from the server.

Related to https://github.com/coala/corobo/issues/156

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by yukiisbored** [comment]
The SSH key and execution of the script will be added from the CI side since it doesn't use a configuration file inside the repository.

**Comment by yukiisbored** [comment]
Another thing, the docker registry automated build should be removed and recreated into a regular repository and have the CI do the build and push to the docker registry

**Comment by meetmangukiya** [comment]
ack 3976ea67171a5c9af27d803b5e186e056533c23f @yukiisbored rebase

**Comment by meetmangukiya** [comment]
@rultor merge

**Comment by meetmangukiya** [comment]
ack 6f41a7b

**Comment by meetmangukiya** [comment]
@rultor merge

**Pull request merged**
