### PR TITLE
README.md: Updated README with Zulip; Fixes Issue: https://github.com/coala/corobo/issues/385

### PR DESCRIPTION
**Pull request by hrithik-jha**
# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by hrithik-jha** [comment]
Can someone let me know what I should be changing? Thanks.

**Comment by hrithik-jha** [comment]
@nvzard Should I create a new commit?

**Comment by hrithik-jha** [comment]
@jayvdb Sorry for the mishap. I can't reopen this PR as it says my branch was force pushed or recreated. What should I do to fix this? Also after amending the commit message Travis still didn't approve of the commit, so what should I do about that? Thank you for your patience.

**Comment by jayvdb** [comment]
Come on to https://coala.io/chat and ask for help.

**Pull request closed without merging**
