### PR TITLE
labhub.py: Add comma in eligility_conditions

### PR DESCRIPTION
**Pull request by solutusimmensus**
This change makes the GCI related condition of corobo message to appear
in a new line.

Closes https://github.com/coala/corobo/issues/310

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by prnvdixit** [comment]
Also, change "last condition" to "GCI related condition" in the commit description as this condition might not remain "last" forever 😉.

**Comment by solutusimmensus** [comment]
Good points. I've amended commit message and updated the description of this pull request.

**Comment by solutusimmensus** [comment]
Perhaps it's a good idea to mention the difference between "Fixes" and "Closes" in [Git tutorial](http://api.coala.io/en/latest/Developers/Git_Basics.html).

**Comment by prnvdixit** [comment]
Please, squash your commits.... :+1:...
Also, Newcomers guide does specify the difference :wink:, still IMO there is some confusion in the terminology. There is already an issue pending to clear the same - I can understand the confusion, but it would be fine after that issue is closed :smile:

**Comment by Monal5031** [comment]
@prnvdixit Please mark PRs as wip after review so that the ones already reviewed don't appear in the review queue at `coala.io/review`

**Comment by solutusimmensus** [comment]
Sorry, it took some time but I'm hoping this time it's okay.

**Comment by prnvdixit** [comment]
ack 72dac7e21f5d9792c0bd69b5390c6bfe56b840fb

**Comment by meetmangukiya** [comment]
@rultor merge

**Comment by RJ722** [comment]
Wasn't it supposed to be a GCI issue, or are students allowed to claim them from now on?

**Comment by RJ722** [comment]
Never mind saw the labels! 😅

**Comment by solutusimmensus** [comment]
Thanks or the review, guys!

**Pull request merged**
