### PR TITLE
labhub: Add missing whitespace

### PR DESCRIPTION
**Pull request by vaibhavgarg11**
changed ourcommunity to our community
closes https://github.com/coala/corobo/issues/214

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by vaibhavgarg11** [comment]
Added the changes as requested, sorry for the lousy commit in the first place.

**Comment by meetmangukiya** [comment]
Added -> Add. 

Also, changing PR title is not equivalent to changing commit messages

**Comment by sidharthskumar** [comment]
@vaibhavgarg11 hey the change looks good , before i pull request i always go through [this](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) unless or until am sure about the commit message :D

**Comment by vaibhavgarg11** [comment]
@meetmangukiya sorry about that I'll try to fix it. The thing is I made these changes directly on github so I am having some trouble finding how to change the commit message.

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 you have two commits now. You need to squash those in one. 

> The thing is I made these changes directly on github so I am having some trouble finding how to change the commit message.

Github UI doesn't allow changing commit messages. Git is best used with the git cli. You should read this http://coala.io/git

**Comment by vaibhavgarg11** [comment]
@meetmangukiya I originally inteded to do that but I couldn't  find the file path. Do i also need to clone https://github.com/coala/corobo inorder to do that

**Comment by vaibhavgarg11** [comment]
@meetmangukiya can you help we with a issue I'm facing using git
so I cloned the corobo repository in order to change the commit message
but when I use `git branch` command in order to change to the branch that I had made changes to it only shows the master branch

**Comment by adhikasp** [comment]
@vaibhavgarg11 you need to `git fetch --all` first so you get all the remote branches.

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 you didn't squash correctly

**Comment by vaibhavgarg11** [comment]
I tried to but I got a error saying cannot squash without a previous commit.

**Comment by vaibhavgarg11** [comment]
@meetmangukiya please suggest me what should I do further ?

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 :
```
git checkout patch-1 # checking out the branch
# to sync with remote
git fetch origin
git rebase origin/patch-1
# remove extra commits and commit again
git reset HEAD~4
# assuming you are in repo root
git add plugins/labhub.py
git commit
```

**Comment by vaibhavgarg11** [comment]
@meetmangukiya done

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 this is just getting worse, I think it'd be better to create a new PR from a new branch branched off master. ;)

**Comment by vaibhavgarg11** [comment]
Created new PR #266

**Pull request closed without merging**
