### PR TITLE
removed comment in webservices.raml regarding gitlab.com/coala/landin…

### PR DESCRIPTION
**Pull request by mikebmc**
…g/merge_request/39

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by jayvdb** [comment]
Thanks @mikebmc , that change is good of course.
Could you amend your commit so that the commit message complies with https://coala.io/commit .  Otherwise the bots go mad and dont let us merge it.

**Comment by mikebmc** [comment]
@jayvdb thanks! I'd noticed the errors on my way out the door yesterday, but didn't have time to correct them. Travis yelled at me again, but also passed the test? I think the issue is that I failed to use `--force` in an intermediary push, and it auto generated a commit with too long a message. I will look into fixing that this afternoon.

I'd forgotten about gizoogle. Should I look into why that test can't connect?

**Comment by jayvdb** [comment]
Dont worry about gizoogle ; our bots sometimes cant get a network connection happening to all the links in the repo.  It has had a lot of development without a release lately, but with GSoC over I think we'll get a bit of release management happening.

You have four commits in https://github.com/coala/corobo/pull/618/commits 

You'll need to squash them into one commit.  https://coala.io/git may be of some help.  If you're stuck, come onto https://coala.io/chat and we'll step through the process.  But please dont close the PR and start a new one, delete your fork or delete your branch.  A PR is always fixable until you, and to be useful in coala you need those skills, and we'll happily help you get those skills - but we dont want to keep getting PRs from developers who dont keep their work tidy, as that creates continual work for maintainers and makes it harder to review patches.

**Comment by jayvdb** [comment]
Great.  Final step... 

The commit message needs to comply with https://coala.io/commit .

Note this is a Closes , not a Fixes , as it isnt a bug.

**Comment by mikebmc** [comment]
@jayvdb thanks for your patience! Hopefully this last commit is up to snuff

**Comment by jayvdb** [comment]
Ack 7ec1088

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
