### PR TITLE
coatils: Add ls bears cmd

### PR DESCRIPTION
**Pull request by meetmangukiya**
Closes https://github.com/coala/corobo/issues/16

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by SanketDG** [comment]
lgtm :+1:

**Comment by SanketDG** [comment]
ack 5507b8d

**Comment by meetmangukiya** [comment]
ack 2b90d719836096d1d72fe7d15bb6446b45744cdc

**Comment by meetmangukiya** [comment]
@rultor merge

**Pull request merged**
