### PR TITLE
coala_lowercase_c: Add coala_lowercase_c plugin

### PR DESCRIPTION
**Pull request by meetmangukiya**
Closes https://github.com/coala/corobo/issues/129

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by Udayan12167** [comment]
ack https://github.com/coala/corobo/pull/130/commits/10bf4833c778de2eac67ec4b6adbb0363c939df9

**Comment by Udayan12167** [comment]
@meetmangukiya rebase and you can merge this.

**Comment by meetmangukiya** [comment]
raeck 8ba536926370a8cb26baeccad17e06f0444e0899

**Comment by meetmangukiya** [comment]
reack 8ba536926370a8cb26baeccad17e06f0444e0899

**Comment by meetmangukiya** [comment]
ack 8ba536926370a8cb26baeccad17e06f0444e0899

**Comment by meetmangukiya** [comment]
@rultor merge

**Pull request merged**
