### PR TITLE
labhub.py: Fix spelling mistake

### PR DESCRIPTION
**Pull request by andrewda**
This changes the spelling of `create_issut_cmd` to `create_issue_cmd`.

Closes https://github.com/coala/corobo/issues/362

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by jayvdb** [comment]
ack https://github.com/coala/corobo/pull/409/commits/900c5613471a75451f6dfd521406f352948ca605

**Comment by jayvdb** [comment]
@rultor merge

**Comment by prnvdixit** [comment]
@andrewda BTW Please, use "Fixes" instead of "Closes" for issues labelled "bug". You can refer to https://coala.io/commit to know more about this. Otherwise, great work :+1:.

**Comment by andrewda** [comment]
@prnvdixit Will do. Thanks!

**Pull request merged**
