### PR TITLE
changes to labhub.py :to add an extra message when newcomer tries to assign medium issues

### LINKED ISSUE #296: Mention that users need to be a developer (and point to the requirements) if they try to assign a medium issue
Opened by @adtac at [gitter/coala/coala](https://gitter.im/coala/coala?at=59c7771dcfeed2eb654459a4)

### PR DESCRIPTION
**Pull request by syntax-explorer**
This mentions that the medium level and unlabelled issues cannot be
assigned to newcomers and they need to complete the developer
process to get themselves assign such issues.

closes #296

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by syntax-explorer** [comment]
can anybody merge this PR. It has no issues

**Comment by syntax-explorer** [comment]
@yashovardhanagrawal i changed what u said

**Comment by yashovardhanagrawal** [comment]
don't change the title 😄 
you have to change the message using git command 😛 

do one thing, 

read the git tutorial here: http://api.coala.io/en/latest/Developers/Git_Basics.html

**Comment by syntax-explorer** [comment]
thanks @yashovardhanagrawal

**Comment by yashovardhanagrawal** [comment]
okay, git might be overwhelming as this is your first time, I will give you some tutorials on how to learn it:

https://www.codecademy.com/learn/learn-git (first complete this to get a overview how and what you do using git)

then try any of these tutorials:
https://www.udemy.com/short-and-sweet-get-started-with-git-and-github-right-now/
https://www.udemy.com/git-started-with-github/

you may also download GitHub Desktop, as it is UI based and much easier to use


that's all I can do to help you 😅 

starting with open source can be overwhelming I know but keep patience you will eventually learn a lot and that will definitely be good for you 😉

**Comment by shaipranesh11** [comment]
ack 23998bfc

**Comment by shaipranesh11** [comment]
@rultor merge

**Pull request merged**
