### PR TITLE
labhup.py: Editing the Eligibilty Error

### PR DESCRIPTION
**Pull request by prashant0598**
# Reviewers Checklist

- [x] Appropriate logging is done.
- [x] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by meetmangukiya** [comment]
This isn't what was asked in the issue https://github.com/coala/corobo/issues/328 

Currently the bot returns all the reasons, this issue is about making the bot tell us exact reason instead of stating potential reasons for the failure.

**Comment by prashant0598** [comment]
@meetmangukiya How should i check for the case:
 A newcomer cannot be assigned to an issue with a difficulty level higher than newcomer or difficulty/low.

**Comment by RaiVaibhav** [comment]
>A newcomer cannot be assigned to an issue with a difficulty level higher than newcomer or difficulty/low.

I think maybe, this will be already used in the code as I didn't  read the code , IMO what you can do is use the `API` and using basic operators like (and, or) and basic statements like `if else` to check if the person is in `https://github.com/orgs/coala/teams/coala-newcomers/members` then he can't get assign and assign and you also have to check using `if else` that whether the person is already in some `maintainer` or `developer` team if yes then he is eligible

## Like wise do same for others messages and don't forgot to create a test for it.

**Comment by jayvdb** [comment]
unack https://github.com/coala/corobo/pull/338/commits/04d0f05d485f127e9db2758bd30fbe87a1582388

**Comment by jayvdb** [comment]
@prashant0598, are you going to re-do this ?  The important point is https://github.com/coala/corobo/pull/338#issuecomment-345435638 ; this patch doesnt do what was requested.
if not, please close and unassign, so that a high school student can do this task as part of Google Code in.

**Comment by sks444** [comment]
@jayvdb, In case @prashant0598 unassign this issue can I give it a try?

**Comment by RaiVaibhav** [comment]
>if not, please close and unassign, so that a high school student can do this task as part of Google Code in.

@sks444  It will count as a gci task if prashant didn't reply :)

**Comment by prashant0598** [comment]
@jayvdb @RaiVaibhav  actually i had my exams so was not able to do it but now i am already working on this

**Comment by jayvdb** [comment]
@prashant0598 , your github activity log says you are busy doing other things in other projects.  Come back to coala when you are serious.

**Comment by prashant0598** [comment]
@jayvdb sorry for replying late but i thought this had been added as a gci issue so did not finished it and i am serious about coala but because of end semester exams i was not able to devote full time.

**Pull request closed without merging**
