### PR TITLE
.travis.yml: Add coala-ci checks

### PR DESCRIPTION
**Pull request by bhavishyagopesh**
Calls `coala --ci` from CI

Closes https://github.com/coala/corobo/issues/435

# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by LifetimeAlone** [comment]
Please, rebase your branch using `git rebase` (do not press github 'update branch' button, it's evil ;D)
Everything else is alright :+1:

**Comment by bhavishyagopesh** [comment]
@LifetimeAlone  rebased

**Comment by jayvdb** [comment]
needs a rebase again, if you are around.

**Comment by jayvdb** [comment]
Err , travis is already running `coala --non-interactive` . see https://github.com/coala/corobo/blob/117c747/.travis.yml#L24

**Comment by jayvdb** [comment]
I'm not sure how this helps at all.  left a comment at https://github.com/coala/corobo/issues/435#issuecomment-348788076

**Comment by jayvdb** [comment]
The bug was bogus; this only slows down the build.

**Pull request closed without merging**
