### PR TITLE
remove ship it emoticon

### PR DESCRIPTION
**Pull request by ihsavru**
# Reviewers Checklist

- [ ] Appropriate logging is done.
- [ ] Appropriate error responses.
- [ ] Handle every possible exception.
- [ ] Make sure there is a docstring in the command functions. Hint: Lookout for
  `botcmd` and `re_botcmd` decorators.
- [ ] See that 100% coverage is there.
- [ ] See to it that mocking is not done where it is not necessary.

### CODE REVIEW

**Comment by meetmangukiya** [comment]
Hey @ihsavru thanks for the contribution, please fix the following:
1. Fix the tests as well, it should be easy. Remove `:shipit: ` from https://github.com/coala/corobo/blob/master/tests/ship_it_test.py#L9 as well, note that you are supposed to remove the space after `:shipit:` as well.
2. Commit message isn't according to our standards, see http://coala.io/commit . Change it to something like `ship_it: Remove ...`   

After this is completed, we can merge it :smile:

**Comment by meetmangukiya** [comment]
@ihsavru both should go into same commit, please squash the commits, http://coala.io/squash,

Use the second commit message and make the `r` in remove capital `Remove`

**Comment by ihsavru** [comment]
I think I squashed the wrong commits? Sorry :sweat_smile:

**Comment by meetmangukiya** [comment]
@ihsavru yeah, you did wrong squash :sweat: 

Fix:
1. `git checkout shipit` (assuming local branch name is same as remote branch name)
2. `git reset HEAD~2`
3. `git add plugins/ship_it.py tests/ship_it_test.py`
4. `git commit` - Use the same message that I approved before ;)
5. perform a rebase against master

**Comment by ihsavru** [comment]
can you explain step 5 more please?

**Comment by meetmangukiya** [comment]
ack 		12746d0

**Comment by meetmangukiya** [comment]
@rultor merge

**Comment by meetmangukiya** [comment]
Congratulations on your first contribution to corobo @ihsavru :smiley:

**Pull request merged**
